### ISSUE TITLE
Information after registration that the user has to verify

### ISSUE THREAD

**Issue by kft-a** [zznicole/shopping-list#46]

**Comment by kft-a** [comment]
After registering an account, the user should be presented with either:
1. Successful registration, please check your email for a verification link, and
2. Error stating that registration was not possible due to error message from server.

Not sure if this would be a new component or just a message in the login component.

**Comment by zznicole** [comment]
In this case, a clear instruction via a message seems more appropriate, if 1) direct the user to check user's email for the verification link. otherwise if it's  2) state what causes the error, and direct user to next step which user should take to process the signup,  for instance, reloading the sign-in page and with a message to advice user to re-enter the sign-in info if the error caused by form validations.

**Comment by kft-a** [comment]
Fixed and merged with #2c32f32 on master
